### ISSUE TITLE
a small typo on README

### ISSUE THREAD

**Issue by oonid** [hyperledger-labs/university-course#16]
Hi,
I found this small typo on [README.md](https://github.com/hyperledger-labs/university-course/blob/master/README.md).

> This course is a 6-7.5 ECTS master level course that assumes 3 hours of theory per week + **1.5 weeks** of practical classes (laboratory) per week.

it should be:

> This course is a 6-7.5 ECTS master level course that assumes 3 hours of theory per week + 1.5 hours of practical classes (laboratory) per week.

thank you for sharing the great content!

**Comment by RafaelAPB** [comment]
Thank you very much @oonid. I'll open a PR. Please feel free to further contribute. Cheers!|
